name: Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Cache yarn packages
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Install gems
        run: bundle install
      - name: Check Code
        run: ./bin/check_code
